version: '3'
services:
  nginx:
    image: docker.io/library/nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
#      - ./upload:/var/www/html/upload
      - ./pod/nginx:/etc/nginx/conf.d
    depends_on:
      - db
      - php
        # dbコンテナの状態がhealthyになるまで待つ (dbコンテナの準備が完全に終了するまで)
#        condition: service_healthy

  db:
    image: docker.io/library/mysql:8.4.4
    ports:
      - 3306:3306
    volumes:
      - ./pod/db/data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
    env_file:
      # Environmental variables
      # - MYSQL_ROOT_PASSWORD
      - pod/db/variables.env

  php:
    build:
      # Dockerfileを格納するフォルダのパス
      context: ./pod/php
      # Dockerfileのファイル名
      # dockerfile: Dockerfile
    volumes:
      # ./srcフォルダをコンテナ内の/var/www/htmlにマウント
      - ./src:/var/www/html
